### ISSUE TITLE
ayacc gets stuck creating an infinitely large file after encountering a comment in an action

### ISSUE THREAD

**Issue by ghuysmans** [Ada-France/ayacc#6]
Here's a minimal reproducer:
```yacc
%token X
%%
rule : X { null; --boom! };
%%
```

I'm running ayacc 1.3.0.

**Comment by stcarrez** [comment]
Due to the Ada comment in the yacc rule, the ayacc parser skips the complete line including the `};` which indicates the end of the rule.

I'll fix that and with your current yacc grammar, you will get the error:

```
Ayacc: missing end of action token '}'
rule : X { null; --boom! };
 4      %%
        -^
```

You must put the `}` on the next line.

The next error in your yacc grammar is that you don't declare the `YYSType`. This is required for the generated `XXX_tokens` package, and as it is this will not compiled. ayacc 1.3 does not tell you about the issue and it aborts with:

```
Ayacc: Internal Error, Please Submit an LCR.
```

Change your grammar to:

```
%token X
{ type YYSType is new Integer; }
%%
rule : X { null; --boom!
 };
%%
```

I'll fix ayacc to report a clever error message.

**Comment by ghuysmans** [comment]
Thanks for your help!
